#!/bin/bash

echo "=> Linting Ansible Code"
fail_ansible=0
for f in `find . -name "*.yml"`; do
    echo "==> LINTING $f"
    ansible-lint $f
    rc=$?
    if [[ $rc != 0 ]]; then
        echo "==> LINTING FAIL: $f"
        fail_ansible=1
    fi
done

echo "=> Run Ansible"
fail_provision=0
ansible-playbook test.yml --connection=local
rc=$?
if [[ $rc != 0 ]]; then
    echo "=> PROVISIONING FAIL"
    fail_provision=1
fi

echo "=> Verify Environment"
fail_spec=0
rake spec
rc=$?
if [[ $rc != 0 ]]; then
    echo "=> TESTING FAIL"
    fail_spec=1
fi

if [[ $fail_ansible == 1 || $fail_provision == 1 || $fail_spec == 1 ]]; then
    echo "=> FAIL FAIL FAIL"
    exit 1
else
    echo "=> SUCCESS"
fi
